import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateRecognitionResult} from '../dist/ai-recognition.mjs';

const valid={schemaVersion:1,kind:'party',slots:Array.from({length:6},(_,index)=>({slot:index+1,name:index===0?'달코퀸':null,item:null,ability:null,nature:null,moves:[],evs:[2,32,0,0,0,32],confidence:.9,notes:''}))};
const result=validateRecognitionResult(structuredClone(valid));
assert.equal(result.slots.length,6);
assert.equal(result.slots[0].name,'달코퀸');
assert.deepEqual(result.slots[0].evs,[2,32,0,0,0,32]);
assert.throws(()=>validateRecognitionResult({...valid,slots:valid.slots.slice(1)}));
assert.throws(()=>validateRecognitionResult({...valid,slots:valid.slots.map((slot,index)=>index?slot:{...slot,evs:[33,0,0,0,0,0]})}));
const recognizer=fs.readFileSync(new URL('../aws/recognizer.py',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('../dist/ai-recognition.mjs',import.meta.url),'utf8');
const template=JSON.parse(fs.readFileSync(new URL('../aws/template.json',import.meta.url),'utf8'));
assert.match(recognizer,/UpdateExpression='SET expiresAt = :ttl ADD requests :one'/);
assert.doesNotMatch(recognizer,/UpdateExpression='ADD requests :one SET expiresAt = :ttl'/);
assert.match(client,/REQUEST_TIMEOUT_MS=135000/);
assert.match(client,/MAX_EDGE=2560/);
assert.match(client,/buildLeadContactSheet/);
assert.match(client,/buildPartyContactSheet/);
assert.match(client,/Promise\.all\(selected\.map\(async file=>\(await buildLeadContactSheet/);
const sheet=fs.readFileSync(new URL('../dist/recognition-contact-sheet.mjs',import.meta.url),'utf8');
assert.match(sheet,/rectDetector\(bitmap, 'mine'\)/);
assert.match(sheet,/rectDetector\(bitmap, 'opp'\)/);
assert.match(sheet,/canvas\.width = cellWidth \* 2/);
assert.match(sheet,/canvas\.height = cellHeight \* 6/);
const fixtureManifest=JSON.parse(fs.readFileSync(new URL('./fixtures/recognition/manifest.json',import.meta.url),'utf8'));
const screenMap=JSON.parse(fs.readFileSync(new URL('../dist/recognition-screen-map.json',import.meta.url),'utf8'));
const partyReferences=screenMap.filter(reference=>reference.kind==='party');
assert.deepEqual(partyReferences.slice(0,6).map(reference=>reference.name),fixtureManifest.party.names);
assert(fs.statSync(new URL('../dist/pokemon-icon-legend.jpg',import.meta.url)).size>100000);
for(const file of Object.keys(fixtureManifest.lead))assert(fs.statSync(new URL(`./fixtures/recognition/${file}`,import.meta.url)).size>1000,file);
assert.equal(fixtureManifest.lead['lead-alolan-ninetales.webp'].mine[4],'알로라 나인테일');
assert.equal(fixtureManifest.party.names.length,6);
assert.equal(fixtureManifest.party.evs.flat().length,36);
assert.equal(fixtureManifest.party.details.length,6);
const pending=Object.values(fixtureManifest.lead).flatMap(value=>[...value.mine,...value.opp]).filter(value=>value?.pending);
assert(pending.length>0,'확정하지 못한 슬롯은 pending으로 명시해야 합니다.');
assert.match(recognizer,/초상화·아이콘/);
assert.match(recognizer,/같은 위치의 동일한 6마리/);
assert.match(recognizer,/gpt-5\.2/);
assert.match(recognizer,/'reasoning':\{'effort':'none'\}/);
assert.match(recognizer,/'verbosity':'low'/);
assert.match(recognizer,/AI가 이 슬롯을 반환하지 않았습니다/);
assert.doesNotMatch(recognizer,/별명만 보이거나 불확실한 값은 null/);
assert.match(recognizer,/urlopen\(req,timeout=110\)/);
assert.equal(template.Resources.RecognitionHandler.Properties.Timeout,120);
const lead={schemaVersion:1,kind:'lead',sides:{mine:structuredClone(valid.slots),opp:structuredClone(valid.slots)}};
assert.equal(validateRecognitionResult(lead).sides.opp.length,6);
assert.throws(()=>validateRecognitionResult({...lead,sides:{mine:lead.sides.mine,opp:lead.sides.opp.slice(1)}}));
console.log(`PASS: 실제 픽스처 8장, 선출 12칸 단일 contact sheet, 파티 6종/36 EV manifest. pending ${pending.length}칸.`);
