import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {generateKeyPairSync,sign} from 'node:crypto';import {pathToFileURL} from 'node:url';
import {draft,makeSet,validSet,validEV,recommend,empiricalCoverage,recommendationCards,calculateStats,damageRolls,classifyKO,battleCalculation,strongestStatMove,damageScenarioResults,speedVariants,teamDefenseMatrix,coverageDelta,resolveMegaForm,applyMegaForm} from '../dist/engine.mjs';
import {buildAdviceInput,validateAdviceResponse} from '../dist/party-advice.mjs';
import {commandPayload} from '../discord/commands.mjs';
import {validVisualFeature,rankVisualCandidates,confidentVisual} from '../dist/recognition.mjs';
import {validateRecognitionResult} from '../dist/ai-recognition.mjs';
import {escapeHtml} from '../dist/ui.mjs';
import {findPokemonMatches} from '../dist/pokemon-search.mjs';
import {loadSavedTeams,partyExport} from '../dist/party-storage.mjs';
import {renderPartyPokemonMatches} from '../dist/party-recognition-ui.mjs';
import {renderLeadPokemonMatches} from '../dist/lead-ui.mjs';
import {loadSetLibrary,addSetsToLibrary,removeSetFromLibrary} from '../dist/set-library.mjs';
import {megaStoneNames,megaItems,hasMegaOption,isMegaItem,filterMegaPokemon} from '../dist/mega-classification.mjs';
import {buildMegaFormIndex,filterFormRows} from '../dist/mega-form-index.mjs';
const root=path.resolve(import.meta.dirname,'..'),D=JSON.parse(fs.readFileSync(root+'/dist/data.json')),O=JSON.parse(fs.readFileSync(root+'/dist/opendata.json'));
assert.equal(commandPayload.length,11);assert.equal(new Set(commandPayload.map(command=>command.name)).size,11);assert(commandPayload.every(command=>command.type===1));
const sprites=JSON.parse(fs.readFileSync(root+'/dist/sprite-map.json'));
{const stones=megaStoneNames(D.master),charizard=D.modes.single.find(x=>x.name==='리자몽'),umbreon=D.modes.single.find(x=>x.name==='블래키');assert(stones.has('리자몽나이트Y'));assert(isMegaItem('리자몽나이트Y',D.master));assert(!isMegaItem('메가안경',D.master));assert(hasMegaOption(charizard,D.master));assert(megaItems(charizard,D.master).every(x=>stones.has(x.name)));assert(!hasMegaOption(umbreon,D.master));assert(filterMegaPokemon(D.modes.single,'mega',D.master).includes(charizard));assert(filterMegaPokemon(D.modes.single,'normal',D.master).includes(umbreon));}
{const images=JSON.parse(fs.readFileSync(root+'/dist/champions-image-map.json')),forms=buildMegaFormIndex(D.modes.single,D.master,images),saved=JSON.parse(fs.readFileSync(root+'/dist/mega-form-index.json')),x=forms.find(p=>p.name==='메가리자몽X'),y=forms.find(p=>p.name==='메가리자몽Y'),garchomp=forms.find(p=>p.name==='메가한카리아스'),garchompZ=forms.find(p=>p.name==='메가한카리아스Z');assert.deepEqual(saved.modes.single,forms);assert.equal(forms.filter(p=>p.name.startsWith('메가리자몽')).length,2);assert.deepEqual(x.types,['불꽃','드래곤']);assert.deepEqual(y.types,['불꽃','비행']);assert.equal(x.megaStone,'리자몽나이트X');assert.equal(y.megaStone,'리자몽나이트Y');assert.equal(x.image,images['메가리자몽X']);assert(garchomp);assert(garchompZ);assert.notEqual(garchomp.name,garchompZ.name);assert.deepEqual(garchompZ.types,['드래곤']);assert.equal(garchompZ.megaStone,'한카리아스나이트Z');assert.equal(garchompZ.image,'champions-images/pokemon-0445-02.webp');assert.deepEqual(filterFormRows(D.modes.single,forms,'mega').filter(p=>p.name.startsWith('메가리자몽')).map(p=>p.name),['메가리자몽X','메가리자몽Y']);assert(filterFormRows(D.modes.single,forms,'normal').every(p=>!p.isMegaForm));assert(findPokemonMatches(filterFormRows(D.modes.single,forms,''),'메가한카리아스Z').some(p=>p.name==='메가한카리아스Z'));}
const currentPokemon=new Set(Object.values(D.modes).flatMap(rows=>rows.map(p=>p.name)));
assert.equal(currentPokemon.size,235);assert.equal(Object.keys(sprites).length,235);
for(const name of currentPokemon){assert(sprites[name]);const file=root+'/dist/'+sprites[name];assert(fs.statSync(file).size>100);assert.equal(fs.readFileSync(file).subarray(1,4).toString(),'PNG')}
for(const mode of ['single','double']){
 const rows=D.modes[mode],open=O.modes[mode];assert.equal(rows.length,235);assert.equal(new Set(rows.map(p=>p.name)).size,235);
 for(const p of rows){assert(D.master.pokemon.some(x=>x[0]===p.name));for(const k of ['items','moves','natures','abilities'])for(const v of p[k]){assert(D.master[k].some(x=>x[0]===v.name));assert(!/[ぁ-ヿ一-龯]/.test(v.name));assert(v.rate>=0&&v.rate<=100)}for(const e of p.evs)assert(validEV(e.name.match(/\d+/g).map(Number)));for(const c of p.counters){assert(D.master.pokemon.some(x=>x[0]===c.name));assert(c.rate>=0&&c.rate<=100);assert(Number.isInteger(c.n)&&c.n>0)}}
 for(const fixed of [[],['블래키'],['한카리아스','따라큐']]){let team=draft(rows,open,fixed,D.master);assert.equal(team.length,6);assert(team.every(s=>validSet(s,rows)));assert.equal(new Set(team.map(s=>s.name)).size,6);assert.equal(new Set(team.filter(s=>s.items).map(s=>s.items)).size,team.filter(s=>s.items).length);assert(fixed.every(n=>team.some(s=>s.name===n)))}
 for(const f of open.frequency){const actual=open.teams.filter(t=>t.team.some(m=>m.name===f.name)).length;assert.equal(f.count,actual);assert.equal(f.rate,Math.round(actual/open.count*1000)/10)}
 for(const t of open.teams){assert.equal(t.team.length,6);for(const m of t.team){assert(D.master.pokemon.some(x=>x[0]===m.name));assert(!m.item||D.master.items.some(x=>x[0]===m.item));assert.deepEqual(Object.keys(m).sort(),['id','item','name'])}}
}
assert(!validEV([32,32,3,0,0,0]));assert(!validEV([33,0,0,0,0,0]));assert(!validEV([null,0,0,0,0,0]));
assert.deepEqual(calculateStats([72,120,98,50,98,72],[2,32,0,0,0,32],D.master.natures.find(x=>x[0]==='고집')),[149,189,118,63,118,124]);
assert.deepEqual(damageRolls(100,100,100,0),Array(15).fill(0));assert.equal(classifyKO(damageRolls(100,100,100,0),100).label,'효과 없음');assert.equal(classifyKO(damageRolls(100,100,100,1),40).label,'난수 1타 93%');assert.equal(classifyKO(damageRolls(100,100,100,1),47).label,'확정 2타');
{const p=D.modes.single.find(x=>x.name==='한카리아스'),z=resolveMegaForm(p,'한카리아스나이트Z',D.master),classic=resolveMegaForm(p,'한카리아스나이트',D.master);assert(z.ok);assert.equal(z.name,'메가한카리아스Z');assert.deepEqual(z.types,['드래곤']);assert.deepEqual(z.baseStats,[108,130,85,141,85,151]);assert(classic.ok);assert.equal(classic.name,'메가한카리아스');assert.notEqual(classic.name,z.name);}
{const z=D.modes.single.find(x=>x.name==='리자몽'),y=resolveMegaForm(z,'리자몽나이트Y',D.master),x=resolveMegaForm(z,'리자몽나이트X',D.master),bad=resolveMegaForm(z,'라이츄나이트X',D.master),applied=applyMegaForm(z,{...makeSet(z),items:'리자몽나이트Y'},D.master);assert(y.ok);assert.equal(y.name,'메가리자몽Y');assert.deepEqual(y.types,['불꽃','비행']);assert.deepEqual(y.baseStats,[78,104,78,159,115,100]);assert.equal(y.ability,null);assert(!y.abilityKnown);assert(x.ok);assert.equal(x.name,'메가리자몽X');assert.deepEqual(x.types,['불꽃','드래곤']);assert(!bad.ok);assert(bad.reason.includes('적용되는 메가스톤이 아니거나'));assert(applied.ok);assert.equal(applied.pokemon.name,'메가리자몽Y');assert.deepEqual(applied.pokemon.abilities,[]);const ambiguous=resolveMegaForm({name:'냐오닉스(수컷)'},'냐오닉스나이트',D.master);assert(!ambiguous.ok);assert(ambiguous.reason.includes('불명확합니다'));}
{const rows=D.modes.single,matrix=teamDefenseMatrix(rows,['한카리아스']);assert.equal(matrix.length,18);assert.equal(matrix.find(x=>x.type==='얼음').cells[0].value,4);const meta=rows.find(x=>x.name==='메타그로스'),delta=coverageDelta(meta,rows,['한카리아스']);assert(delta.repaired.includes('얼음'));assert(delta.afterScore>delta.beforeScore);const full=coverageDelta(meta,rows,rows.slice(0,6).map(p=>p.name));assert(full.replaced);assert.equal(full.members.length,6);assert(full.members.includes(meta.name))}
{const a=D.modes.single.find(x=>x.name==='달코퀸'),d=D.modes.single.find(x=>x.name==='한카리아스'),s=makeSet(a),m=D.master.moves.find(x=>x[0]==='트리플악셀'),c=battleCalculation(a,d,s,m,[0,0,0,0,0,0],D.master);assert(c);assert.equal(c.type,'얼음');assert.equal(c.typeMultiplier,4);assert.equal(c.stab,1);assert.equal(c.result.label,'난수 3타 15%');assert(c.powerIndex>0)}
{const a=D.modes.single.find(x=>x.name==='리자몽'),d=D.modes.single.find(x=>x.name==='한카리아스'),s=makeSet(a),m=D.master.moves.find(x=>x[0]==='화염방사'),c=battleCalculation(a,d,s,m,[0,0,0,0,0,0],D.master),speeds=speedVariants(a,D.master,s);assert.equal(s.items,'리자몽나이트Y');assert.equal(c.mega.name,'메가리자몽Y');assert.equal(c.attackerStats[3],calculateStats([78,104,78,159,115,100],s.evs,D.master.natures.find(x=>x[0]===s.natures))[3]);assert.equal(c.abilityMultiplier,1);assert.equal(speeds[0].mega.name,'메가리자몽Y');}
{const a=D.modes.single.find(x=>x.name==='리자몽'),d=D.modes.single.find(x=>x.name==='한카리아스'),s=makeSet(a),special=D.master.moves.find(x=>x[0]==='화염방사'),physical=D.master.moves.find(x=>x[0]==='드래곤클로'),boosted=battleCalculation(a,d,s,special,[0,0,0,0,0,0],D.master,{critical:true,helping:true,battery:true}),unboostedPhysical=battleCalculation(a,d,s,physical,[0,0,0,0,0,0],D.master,{battery:true});assert.equal(boosted.specialMultiplier,1.5*1.5*1.3);assert.equal(unboostedPhysical.specialMultiplier,1);}
{const a=D.modes.single.find(x=>x.name==='달코퀸'),d=D.modes.single.find(x=>x.name==='한카리아스'),s=makeSet(a),best=strongestStatMove(a,d,s,D.master),scenarios=damageScenarioResults(a,d,s,best.move,D.master),speeds=speedVariants(a,D.master);assert.equal(best.move[0],'무릎차기');assert.equal(scenarios.length,7);assert.deepEqual(scenarios.map(x=>x.label),['H0 B0','H32 B0','H32 B32','H0 B32','H32 D0','H32 D32','H0 D32']);assert.equal(speeds.length,6);assert(speeds[0].value>speeds[1].value);assert.equal(speeds[3].value,Math.floor(speeds[0].value*1.5))}
{const p=D.modes.single.find(x=>x.name==='달코퀸'),custom={...draft(D.modes.single,O.modes.single,['달코퀸'],D.master)[0],moves:['10만마력']};assert(!validSet(custom,D.modes.single));assert(validSet(custom,D.modes.single,D.master));assert(p.moves.every(x=>x.name!=='10만마력'))}
let code=fs.readFileSync(root+'/dist/app.js','utf8').replace(/\r\n/g,'\n'),recognitionCode=fs.readFileSync(root+'/dist/recognition.mjs','utf8'),uiTemplatesCode=fs.readFileSync(root+'/dist/ui-templates.mjs','utf8'),calculatorCode=fs.readFileSync(root+'/dist/calculator.mjs','utf8');
assert(calculatorCode.includes('searchRows().map'));assert(calculatorCode.includes('baseAttacker.isMegaForm'));
assert.equal(escapeHtml('<b>"달콤" & 봇</b>'),'&lt;b&gt;&quot;달콤&quot; &amp; 봇&lt;/b&gt;');
{const rows=D.modes.single;for(const query of ['나인테일','알로라 나인테일','나인테일 알로라폼']){const matches=findPokemonMatches(rows,query);assert(matches.some(p=>p.name==='알로라 나인테일'),query)}assert.equal(findPokemonMatches(rows,'나인테일')[0].name,'나인테일');const target={innerHTML:''},matches=findPokemonMatches(rows,'나인테일 알로라폼');renderPartyPokemonMatches(target,matches,2,escapeHtml);assert(target.innerHTML.includes('data-ocrcandidate="2"'));assert(target.innerHTML.includes('data-name="알로라 나인테일"'));renderLeadPokemonMatches(target,matches,'opp',4,escapeHtml);assert(target.innerHTML.includes('data-leadside="opp"'));assert(target.innerHTML.includes('data-leadindex="4"'));assert(target.innerHTML.includes('data-leadname="알로라 나인테일"'))}
{const memory=new Map([['champions-party-v1',JSON.stringify({single:[makeSet(D.modes.single[0]),{name:'없는포켓몬'},null,null,null,null],double:Array(6).fill(null)})]]),storage={getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)};const restored=loadSavedTeams(storage,(set,mode)=>validSet(set,D.modes[mode],D.master));assert(restored.repaired);assert(restored.teams.single[0]);assert.equal(restored.teams.single[1],null);assert(memory.has('champions-party-v1-backup'));assert.equal(partyExport('single',D.date,restored.teams.single).team[0].name,restored.teams.single[0].name)}
{const set=makeSet(D.modes.single[0]),storage={getItem:()=>null,setItem:()=>{}},added=addSetsToLibrary([], [set],'single',1);assert.equal(added.length,1);assert.equal(loadSetLibrary(storage,()=>true).length,0);assert.equal(removeSetFromLibrary(added,added[0].id).length,0)}
assert(code.includes('runAIRecognition'));
const feature={area:.2,...Object.fromEntries(Object.entries({hue:12,sv:16,shape:16,geom:4,rgb:3,fine:64}).map(([key,n])=>[key,Array(n).fill(1/Math.sqrt(n))]))};
assert(validVisualFeature(feature));
for(const invalid of [null,{}, {...feature,area:0},{...feature,fine:[NaN]},{...feature,rgb:[1,2,3]}])assert(!validVisualFeature(invalid));
assert.deepEqual(rankVisualCandidates([], [{name:'test',feature}]),[]);
assert.deepEqual(rankVisualCandidates([feature], [{name:'test',feature:{}}]),[]);
assert.equal(rankVisualCandidates([feature], [{name:'test',feature}])[0].name,'test');
for(const scores of [[],[.1],[.1,.1],[.1,.11],[.3,.5],[NaN,.2],[.1,Infinity],[.2,.1]])assert(!confidentVisual(scores.map(score=>({score}))));
assert(confidentVisual([{score:.1},{score:.2}]));
assert(code.includes("monSprite(name,'detail')"));
assert(!code.includes('Tesseract'));assert(!code.includes('createWorker'));
assert(code.includes("document.querySelectorAll('dialog')"));
assert(code.includes("$('teammateRecommendations').innerHTML"));
const css=fs.readFileSync(root+'/dist/style.css','utf8');assert(css.includes('.monpic.missing{background:linear-gradient'));assert(css.includes('.monpic.detail{width:112px;height:112px'));
assert(css.includes('.ocrfallback{'));
const aiSample={schemaVersion:1,kind:'party',slots:Array.from({length:6},(_,i)=>({slot:i+1,name:i?'':'달코퀸',item:null,ability:null,nature:null,moves:[],evs:[2,32,0,0,0,32],confidence:.9,notes:''}))};assert.equal(validateRecognitionResult(aiSample).slots[0].name,'달코퀸');assert.throws(()=>validateRecognitionResult({...aiSample,slots:aiSample.slots.slice(1)}));
assert(code.includes("from './ai-recognition.mjs?v=20'"));assert(code.includes("kind:'party'"));
assert(code.includes('data-detailbuild'));assert(code.includes('rankedChoices(p,k)'));assert(code.includes('performanceHtml(ts)'));
assert(code.includes('setOcrFiles(e.target.files)'));assert(code.includes("mainDrop.addEventListener('drop'"));assert(code.includes('data-imageremove'));assert(code.includes('imageViewer'));assert(code.includes('damageBenchmark(s,target,move,evs)'));
assert(uiTemplatesCode.includes('data-tab="lead"'));assert(code.includes("kind:'lead'"));assert(code.includes('mergeLeadRecognition(result.sides'));assert(code.includes("mode==='single'?3:4"));assert(code.includes('maxDamage(source,target'));
assert(code.includes("recognizeImages({files:[input],mode:inputMode,kind:'lead',leadRectDetector:detectedLeadRects,leadCandidates:local.sides})"));assert(code.includes('인식 완료'));assert(code.includes("result.source==='local'"));
assert(code.includes('if(!result&&useAI)'));assert(code.includes('recognizeLeadOnDevice(input)'));
assert(uiTemplatesCode.includes('data-tab="calculators"'));assert(calculatorCode.includes('export function setupCalculator'));assert(calculatorCode.includes('function runPowerSweep()'));assert(calculatorCode.includes('function runSpeedCompare()'));assert(code.includes('data-leadmatches'));assert(!code.includes('레벨 50'));
assert(code.includes("detailedRow=n=>stats().find"));assert(code.includes('내 파티 평가'));assert(code.includes('AI 파티 제언 받기'));assert(!code.includes('renderAnalysis();renderTypeAnalysis();'));assert(code.includes("const ready=[...lead.mine,...lead.opp].every(x=>x.name&&detailedRow(x.name))"));
assert(code.includes("fetch('champions-icon-map.json')"));assert(!code.includes("fetch('sprite-map.json')"));assert(!code.includes("fetch('sprite-home-map.json')"));assert(code.includes("fetch('recognition-db.json')"));assert(recognitionCode.includes('fineSilhouette'));assert(code.includes('saveLearnedReferences'));
const recognition=JSON.parse(fs.readFileSync(root+'/dist/recognition-db.json')),officialRefs=recognition.references.filter(x=>x.source==='champs.pokedb.tokyo 공식 아이콘');assert.equal(recognition.schemaVersion,3);assert(officialRefs.length>=127);assert.equal(new Set(officialRefs.map(x=>x.name)).size,officialRefs.length);for(const name of ['워시로토무','히트로토무','한카리아스','따라큐','마폭시','핫삼','플라엣테(영원의 꽃)','왕큰부리','달코퀸','프테라','라이츄','포푸니크','님피아','대도각참'])assert(officialRefs.some(x=>x.name===name));assert(!recognition.references.some(x=>['PokeAPI 보조','현재 목록 기본 이미지'].includes(x.source)));for(const ref of recognition.references){assert(currentPokemon.has(ref.name));assert(fs.statSync(root+'/dist/'+ref.src).size>100)}
const html=fs.readFileSync(root+'/dist/index.html','utf8'),manifest=JSON.parse(fs.readFileSync(root+'/dist/manifest.webmanifest')),version=JSON.parse(fs.readFileSync(root+'/dist/version.json')),pokedexInfo=JSON.parse(fs.readFileSync(root+'/dist/pokedex-details.json','utf8')),moveInfo=JSON.parse(fs.readFileSync(root+'/dist/move-details.json','utf8'));assert(html.includes('<title>포챔스 달콤아 봇</title>'));assert(html.includes('assets/dalkoma-logo-192.png'));assert(html.includes('dalkoma-favicon.png?v=16'));assert(html.includes('<strong class="appversion">v33</strong>'));assert(html.includes('id="imageFile" accept="image/png,image/jpeg,image/webp" multiple'));assert(!html.includes('id="screenType"'));assert(html.includes('style.css?v=33'));assert(html.includes('app.js?v=33'));assert(html.includes('id="seasonFilter"'));assert(html.includes('id="usageRanking"'));assert(html.includes('data-tab="dex"'));for(const category of ['pokemon','moves','abilities','items'])assert(html.includes(`data-dexcategory="${category}"`));assert(code.includes("fetch('seasons/index.json')"));assert(code.includes("fetch('pokedex-details.json')"));assert(code.includes("fetch('move-details.json')"));assert(code.includes("salamence:'보만다'"));assert.equal(pokedexInfo.count,344);assert.equal(pokedexInfo.total,344);assert.equal(pokedexInfo.failures.length,0);for(const row of D.master.pokemon){const info=pokedexInfo.details[row[0]];assert(info);assert(Number.isFinite(info.height));assert(Number.isFinite(info.weight));assert(info.sourceId)}assert(pokedexInfo.details['메가몰드류'].abilities.includes('관통드릴'));assert.equal(moveInfo.count,D.master.moves.length);assert.equal(moveInfo.total,D.master.moves.length);assert.equal(moveInfo.failures.length,0);for(const row of D.master.moves){assert(moveInfo.details[row[0]]?.effect);assert.notEqual(moveInfo.details[row[0]].effect,'0')}for(const marker of ['data-movefilter="category"','data-movefilter="performance"','data-movefilter="property"','data-itemcategory','data-abilitypokemon'])assert(code.includes(marker));assert.equal(manifest.name,'포챔스 달콤아 봇');assert.equal(version.version,'v33');assert.equal(version.builtAt,'2026-09-15');assert.equal(version.name,'포챔스 달콤아 봇');for(const icon of ['dalkoma-favicon.png','dalkoma-apple-touch.png','dalkoma-logo-192.png','dalkoma-logo-512.png'])assert(fs.statSync(root+'/dist/assets/'+icon).size>100);assert(!code.includes("source:'PokeAPI 보조'"));assert(!code.includes('키 미제공 · 몸무게 미제공'));
for(const section of ['builder','meta','import'])assert(html.includes(`id="${section}"`));assert(!html.includes('data-tab="ranked"'));assert(uiTemplatesCode.includes('id="coverage"'));assert(uiTemplatesCode.includes('id="library"'));assert(uiTemplatesCode.includes('id="lead"'));assert(uiTemplatesCode.includes('id="calculators"'));
for(const moduleName of ['recognition.mjs','ai-recognition.mjs','recognition-merge.mjs','ui.mjs'])assert(code.includes(`./${moduleName}?v=20`));assert(code.includes('./calculator.mjs?v=28'));assert(code.includes('./engine.mjs?v=28'));assert(code.includes('./ui-templates.mjs?v=28'));assert(code.includes('./season-stats.mjs?v=4'));
const deploy=fs.readFileSync(root+'/aws/deploy.py','utf8'),recognizer=fs.readFileSync(root+'/aws/recognizer.py','utf8');assert(deploy.includes("'no-cache, no-store, must-revalidate'"));assert(deploy.includes("'invalidation-completed'"));assert(deploy.includes('OPENAI_API_KEY'));assert(deploy.includes('MaxDailyRecognitionRequests'));assert(recognizer.includes("'store':False"));assert(recognizer.includes("'max_output_tokens':1600"));assert(recognizer.includes('consume_quota()'));
for(const m of ['single','double']){const z=D.modes[m].find(x=>x.name==='리자몽');assert.equal(z.items[0].name,'리자몽나이트Y');assert.equal(z.items[1].name,'리자몽나이트X');assert(z.items[0].rate>z.items[1].rate)}
const spriteSync=fs.readFileSync(root+'/scripts/sync_pokeapi_sprites.py','utf8'),championsSync=fs.readFileSync(root+'/scripts/sync_champions_icons.py','utf8');assert(spriteSync.includes('pokemon/shiny'));assert(spriteSync.includes('pokemon/other/home/shiny'));assert(spriteSync.includes('sprite-home-map.json'));assert(!spriteSync.includes('RECOGNITION_DB'));assert(championsSync.includes('champs.pokedb.tokyo'));assert(championsSync.includes('SUPPLEMENTAL'));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'champ-bot-test-'));
try{
 for(const [src,name] of [['discord/handler.mjs','handler.mjs'],['dist/engine.mjs','engine.mjs'],['dist/types.mjs','types.mjs'],['dist/data.json','data.json'],['dist/opendata.json','opendata.json'],['dist/pokedex-details.json','pokedex-details.json'],['dist/learnsets.json','learnsets.json'],['dist/move-details.json','move-details.json']])fs.copyFileSync(root+'/'+src,temp+'/'+name);
 const {publicKey,privateKey}=generateKeyPairSync('ed25519');process.env.DISCORD_PUBLIC_KEY=publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex');delete process.env.APP_URL;
 const {handler}=await import(pathToFileURL(temp+'/handler.mjs'));
 const event=(value)=>{const body=JSON.stringify(value),ts=String(Math.floor(Date.now()/1000));return {body,headers:{'x-signature-timestamp':ts,'x-signature-ed25519':sign(null,Buffer.from(ts+body),privateKey).toString('hex')}}};
 assert.equal((await handler({body:'{}',headers:{}})).statusCode,401);
 assert.equal(JSON.parse((await handler(event({type:1}))).body).type,1);
 for(const name of ['메타','추천','파티','웹앱','스크린샷']){const res=await handler(event({type:2,data:{name,options:[]}}));assert.equal(res.statusCode,200);const data=JSON.parse(res.body).data;assert.equal(data.flags,64);assert(data.content.length<=2000);assert(data.content.length>30)}
 const calculator=JSON.parse((await handler(event({type:2,data:{name:'계산기',options:[{name:'공격포켓몬',value:'달코퀸'},{name:'방어포켓몬',value:'한카리아스'},{name:'기술',value:'트리플악셀'},{name:'방어배분',value:'zero'}]}}))).body).data;assert.equal(calculator.flags,64);assert(calculator.content.includes('난수'));assert(calculator.content.includes('타입상성 ×4'));assert(calculator.content.includes('결정력 지수'));
 const megaCalculator=JSON.parse((await handler(event({type:2,data:{name:'계산기',options:[{name:'공격포켓몬',value:'리자몽'},{name:'방어포켓몬',value:'한카리아스'},{name:'기술',value:'화염방사'},{name:'방어배분',value:'zero'}]}}))).body).data;assert(megaCalculator.content.includes('적용 메가폼: **메가리자몽Y**'));assert(megaCalculator.content.includes('메가 특성 자료 미등재'));
 const garchompZCalculator=JSON.parse((await handler(event({type:2,data:{name:'계산기',options:[{name:'공격포켓몬',value:'한카리아스'},{name:'방어포켓몬',value:'블래키'},{name:'기술',value:'지진'},{name:'공격도구',value:'한카리아스나이트Z'},{name:'방어배분',value:'zero'}]}}))).body).data;assert(garchompZCalculator.content.includes('적용 메가폼: **메가한카리아스Z**'));assert(garchompZCalculator.content.includes('(드래곤)'));
 const power=JSON.parse((await handler(event({type:2,data:{name:'결정력계산기',options:[{name:'공격포켓몬',value:'달코퀸'},{name:'방어포켓몬',value:'한카리아스'}]}}))).body).data;assert.equal(power.flags,64);assert(power.content.includes('H0 B0'));assert(power.content.includes('H32 D32'));assert(power.content.includes('채용률 상위 4개 기술'));
 const speed=JSON.parse((await handler(event({type:2,data:{name:'스피드계산기',options:[{name:'공격포켓몬',value:'달코퀸'},{name:'방어포켓몬',value:'한카리아스'}]}}))).body).data;assert.equal(speed.flags,64);assert(speed.content.includes('최속'));assert(speed.content.includes('스카프 무보정'));
 const megaSpeed=JSON.parse((await handler(event({type:2,data:{name:'스피드계산기',options:[{name:'공격포켓몬',value:'리자몽'},{name:'방어포켓몬',value:'블래키'}]}}))).body).data;assert(megaSpeed.content.includes('공격 측 적용 메가폼: **메가리자몽Y**'));assert(megaSpeed.content.includes('메가리자몽Y 152'));
 const moveChoices=JSON.parse((await handler(event({type:4,data:{name:'계산기',options:[{name:'공격포켓몬',value:'달코퀸'},{name:'기술',value:'트리',focused:true}]}}))).body);assert.equal(moveChoices.type,8);assert.equal(moveChoices.data.choices[0].value,'트리플악셀');
 const stoneChoices=JSON.parse((await handler(event({type:4,data:{name:'계산기',options:[{name:'공격포켓몬',value:'한카리아스'},{name:'공격도구',value:'한카리아스',focused:true}]}}))).body);assert.deepEqual(stoneChoices.data.choices.map(x=>x.value),['한카리아스나이트','한카리아스나이트Z']);
 const sample=JSON.parse((await handler(event({type:2,data:{name:'샘플',options:[{name:'포켓몬',value:'블래키'}]}}))).body).data;assert.equal(sample.flags,64);assert(sample.content.includes('종족값:'));assert(sample.content.includes('기술:'));
 const autocomplete=JSON.parse((await handler(event({type:4,data:{name:'샘플',options:[{name:'포켓몬',value:'프레프티르',focused:true}]}}))).body);assert.equal(autocomplete.type,8);assert.equal(autocomplete.data.choices[0].value,'프레프티르');assert(autocomplete.data.choices[0].name.includes('235위'));
 const dexAutocomplete=JSON.parse((await handler(event({type:4,data:{name:'도감',options:[{name:'분류',value:'abilities'},{name:'검색어',value:'접촉 기술',focused:true}]}}))).body);assert(dexAutocomplete.data.choices.some(choice=>choice.value==='까칠한피부'));
 const pokemonDex=JSON.parse((await handler(event({type:2,data:{name:'도감',options:[{name:'분류',value:'pokemon'},{name:'검색어',value:'한카리아스'}]}}))).body).data;assert(pokemonDex.content.includes('배울 수 있는 기술'));assert(pokemonDex.content.includes('종족값:'));
 const moveDex=JSON.parse((await handler(event({type:2,data:{name:'도감',options:[{name:'분류',value:'moves'},{name:'검색어',value:'지진'}]}}))).body).data;assert(moveDex.content.includes('배울 수 있는 포켓몬'));assert(moveDex.content.includes('위력 100'));
 const help=JSON.parse((await handler(event({type:2,data:{name:'명령어',options:[]}}))).body).data;assert.equal(help.flags,undefined);assert(help.content.includes('/웹앱'));assert(help.content.includes('/결정력계산기'));assert(help.content.includes('/스피드계산기'));assert(help.content.includes('/계산기'));assert(help.content.includes('/명령어'));
 const bad=event({type:1});bad.body='{"type":2}';assert.equal((await handler(bad)).statusCode,401);
 const originalFetch=globalThis.fetch,refreshed=structuredClone(O),refreshedDetails=structuredClone(D);refreshed.modes.single.updatedAt='future refresh accepted';refreshed.modes.single.season='M-6';refreshed.modes.double.season='M-6';refreshedDetails.date='web data refresh accepted';process.env.APP_URL='https://example.invalid/app/';globalThis.fetch=async url=>({ok:true,json:async()=>new URL(url).pathname.endsWith('/opendata.json')?refreshed:refreshedDetails});
 try{const refreshedModule=await import(pathToFileURL(temp+'/handler.mjs').href+'?refresh=web');const result=JSON.parse((await refreshedModule.handler(event({type:2,data:{name:'메타',options:[]}}))).body);assert(result.data.content.includes('future refresh accepted'));assert(result.data.content.includes('web data refresh accepted'))}finally{globalThis.fetch=originalFetch;delete process.env.APP_URL}
}finally{fs.rmSync(temp,{recursive:true,force:true})}
console.log('PASS: 470 records; 254 public teams; AI response validation, shared drafts, EV bounds, Discord signatures and eleven commands with autocomplete.');
const {multiplier,assessCandidate,matchup}=await import('../dist/engine.mjs');
assert.equal(multiplier('얼음',['드래곤','땅']),4);
assert.equal(multiplier('땅',['비행','강철']),0);
const single=D.modes.single,get=n=>single.find(p=>p.name===n);
const empirical=empiricalCoverage(get('브리두라스'),single,O.modes.single,['한카리아스']);assert(empirical.covered.some(x=>x.name==='배바닐라'));assert(empirical.score>0);
const double=D.modes.double;const mate=recommend(double,O.modes.double,['달코퀸'],D.master).find(x=>x.p.name==='한카리아스');assert.equal(mate.teammateEvidence[0].direct,1);
const better=assessCandidate(get('메타그로스'),single,O.modes.single,['한카리아스'],D.master);
const worse=assessCandidate(get('하마돈'),single,O.modes.single,['한카리아스'],D.master);
assert(better.defense>worse.defense);
assert(better.repaired.some(x=>x.type==='얼음'));
assert.equal(matchup(get('누리레느'),get('한카리아스'),D.master,{moves:['명상']}).usable,false);
assert.equal(matchup(get('누리레느'),get('한카리아스'),D.master,{moves:['문포스']}).usable,true);
const cards=recommendationCards(single,O.modes.single,['한카리아스'],D.master,[makeSet(get('한카리아스'))]);assert(cards.length&&cards.every(x=>Number.isInteger(x.score)&&x.score>=0&&x.score<=100));assert.deepEqual(cards.map(x=>x.score),[...cards].map(x=>x.score).sort((a,b)=>b-a));const adviceInput=buildAdviceInput({mode:'single',season:'M-6',selected:['한카리아스'],candidates:cards});const advice={schemaVersion:1,advice:[{name:adviceInput.candidates[0].name,summary:'검증된 근거만 사용한 제언',evidenceIds:[adviceInput.candidates[0].evidenceIds[0]]}]};assert.equal(validateAdviceResponse(advice,adviceInput)[0].name,adviceInput.candidates[0].name);assert.throws(()=>validateAdviceResponse({schemaVersion:1,advice:[{...advice.advice[0],evidenceIds:['invalid']}]},adviceInput));
const currentCards=recommendationCards(single,{season:'M-6',frequency:single.slice(0,20).map(p=>({name:p.name,rate:100/Math.sqrt(p.rank)})),teams:[]},['한카리아스'],D.master,[makeSet(get('한카리아스'))]);assert(currentCards[0].advice.includes('M-6 인게임 순위와 동시즌 상세 세팅'));assert(!currentCards[0].advice.includes('시즌 정보 없음'));assert(!currentCards[0].advice.includes('공개 파티 동반 0건'));
assert(fs.readFileSync(root+'/dist/app.js','utf8').includes('recommendationEndpoint'));const recommendationCode=fs.readFileSync(root+'/aws/recommendation.py','utf8');assert(recommendationCode.includes('unsupported model claim'));assert(!recommendationCode.includes("'access-control-allow-origin'"));const recommendationUrl=JSON.parse(fs.readFileSync(root+'/aws/template.json','utf8')).Resources.RecommendationUrl;assert.deepEqual(recommendationUrl.Properties.Cors.AllowMethods,['POST']);assert.deepEqual(recommendationUrl.Properties.Cors.AllowHeaders,['content-type']);
assert(code.includes('data-coverageedit'));assert(code.includes('data-coverageremove'));assert(code.includes('matchupHighlights'));assert(fs.readFileSync(root+'/aws/collector.py','utf8').includes('missingTopDetails'));assert(html.includes('id="dexCategory"'));assert(code.includes('raw.githubusercontent.com/PokeAPI/sprites'));
const calculatorTemplateCode=fs.readFileSync(root+'/dist/ui-templates.mjs','utf8'),calculatorControllerCode=fs.readFileSync(root+'/dist/calculator.mjs','utf8');assert(calculatorTemplateCode.includes('class="calc-sides"'));for(const id of ['calcCritical','calcCharge','calcHelping','calcBattery'])assert(calculatorTemplateCode.includes(`id="${id}"`)&&calculatorControllerCode.includes(`$('${id}').checked`));assert(calculatorControllerCode.includes("attackerRank:Number($('calcAtkRank').value)"));assert(calculatorControllerCode.includes("wall:$('calcWall').value"));
assert(code.includes('recommendationStats=()=>stats()'));assert(code.includes('renderSourceSummary();render()}'));
assert(!fs.existsSync(root+'/dist/vendor/ocr'));
const learnsets=JSON.parse(fs.readFileSync(root+'/dist/learnsets.json','utf8'));assert.equal(learnsets.count,D.master.pokemon.length);assert.equal(learnsets.total,D.master.pokemon.length);assert.equal(learnsets.failures.length,0);for(const row of D.master.pokemon)assert(learnsets.details[row[0]]?.moves.length>0);assert(code.includes("fetch('learnsets.json')"));assert(code.includes('data-movelearners'));assert(code.includes('배울 수 있는 기술 ${learnset.length}개'));assert(code.includes('배울 수 있는 포켓몬 ${filtered.length}/${all.length}종'));
assert(learnsets.details['보만다'].moves.length>24);assert(learnsets.details['야나키'].moves.length>24);for(const marker of ['data-detail-tab="stats"','data-learnerfilter','pokemonDexSort'])assert(code.includes(marker));
console.log('PASS: type priority, actual selected moves, and OCR runtime removal.');
